package:
    name: um_utils
    version: 1.2

source:
    fn: um_utils.tar.gz
    url: https://github.com/SciTools/um_utils

build:
    number: 0

requirements:
    build:
        - python
        - numpy x.x
        - setuptools
        - mule
    run:
        - python
        - numpy x.x
        - mule

test:
    imports:
        - um_utils

about:
    home: https://github.com/SciTools/um_utils
    license: BSD-3
    summary: UM file utilities based on Mule API

extra:
    recipe-maintainers:
        - stevewardle
