package:
    name: um_utils
    version: 2017.06.1

source:
    fn: um_utils.tar.gz
    url: https://github.com/SciTools/um_utils/releases/download/2017.06.1/um_utils.tar.gz

build:
    number: 0
    skip: True # [py3k or win]
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - numpy x.x
        - setuptools
        - mule
    run:
        - python
        - numpy x.x
        - mule

test:
    imports:
        - um_utils

about:
    home: https://github.com/SciTools/um_utils
    license: BSD-3
    summary: UM file utilities based on Mule API

extra:
    recipe-maintainers:
        - stevewardle
