package:
    name: um_packing
    version: 2017.06.1

source:
    fn: um_packing.tar.gz
    url: https://github.com/SciTools/um_packing/releases/download/2017.06.1/um_packing.tar.gz

build:
    number: 0
    skip: True # [py3k or win]
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - numpy x.x
        - setuptools
        - shumlib
    run:
        - python
        - numpy x.x
        - shumlib

test:
    imports:
        - um_packing

about:
    home: https://github.com/SciTools/um_packing
    license: BSD-3
    summary: Extension module for Shumlib (UM) based packing

extra:
    recipe-maintainers:
        - stevewardle
